server:
  port: ${PORT:8085}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LucasRpo/mr_movie.git
          search-paths: config_data_files
          default-label: "main"
  security:
    user:
      name: config
      password: s3rv1c3*
